spring.application.name=spring_security

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql: true

spring.datasource.url=jdbc:postgresql://localhost:5432/auth_users
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

api.security.token.secret=${JWT_SECRET:my-secret-key}







# precisamos configurar os cookies em properties -> timestamp